site_name: "PDNS Manager"
copyright: CC-BY-SA Lukas Metzger
repo_url: "https://github.com/loewexy/pdnsmanager"
theme_dir: "theme"
docs_dir: "content"
site_favicon: "img/favicon.ico"
pages:
    - Home: "index.md"
    - Getting Started: "quickstart.md"
    - Documentation:
        - Add your first domain: "documentation/firstdomain.md"
        - Users: "documentation/users.md"
        - API: "documentation/api.md"
    - Download: "download.md"
    - About: "about.md"

